### ISSUE TITLE
Add support for parcel-plugin-prerenderer

### ISSUE THREAD

**Issue by r0skar** [tom-julux/parcel-plugin-sitemap#8]
Is it possible to add support for [parcel-plugin-prerenderer](https://github.com/ABuffSeagull/parcel-plugin-prerender)? Right now the plugin searches for `html` files as soon as the bundler is done. This means that all `html` files that are generated by the prerenderer are not accounted for.

I guess making this work is not straight forward as there are no hooks that are called after the prerendering is done, but I wanted to raise the issue nevertheless.

**Comment by tom-julux** [comment]
Thanks for raising the issue. Generally it's better to inform the developer, then to just grief about a problem.

Sadly solving this issue is kind of impossible right now, as my plugin can't know when the prerenderer is finished. I tried adding an explaination to the [readme](https://github.com/tom-julux/parcel-plugin-sitemap#timing-using-with-a-prerenderer).

But the prerenderer will most likely always use the same route names, so you can easily create an sitemap manually...
